# ===== Environment / connection =====
base_url : "https://www.monomax.me/api/v2"
verify_flag: false
warning_flag: true

# ===== Credentials =====
username: "testios02"
password: "123456"

username_freetier: "monoprodtestlive01"
password_freetier:  "P@ssw0rd1234"

username_basic: "nowtest02"
password_basic: "123456"

username_standard: "phathtest02"
password_standard: "123456"

default_password: "123456"

# ===== Paths =====
login_path: "/account/login"
get_profile_path: "/account/profile"
packages_path_prefix: "/packages/"
pre_purchase_path: "/packages/verify_prepurchase"
live_tv_path: "/livetv/home"
get_product_path: "/products/"
# ===== Sports demo ids =====
match_id: 06
vod_id: 94

#====== Movie & Series ids =====
series_id: 105383
movie_id: 

# ===== Iteration params =====
platform: [ios, android]
category_ids: [1, 2]
platform_prepurchase:   ios    
SKU:  staging_recurring_sports_1d_1m299  

# ===== Expectations =====
expected_status_code: 200
expected_status: "ok"
#ACCESS_TOKEN:   "yUKrMSJNVRabvjNi5mC3hpbMkUmuDr0DDxoF7Jze"

